baseURL: "https://wuebbena.github.io/web/" 
title: Thorsten Wübbena
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags
 
menu:
    main:
        - name: Publications
          url: publications/
          weight: 1
        - name: Presentations | Poster | Conferences | Workshops
          url: presentations/
          weight: 2 
        - name: Data | Software
          url: data/
          weight: 3 
        - name: Interviews | Clips | Misc
          url: misc/
          weight: 4 
        - name: Projects
          url: projects/
          weight: 5
        - name: Memberships | Committees
          url: memberships/
          weight: 6 
        - name: Employment history
          url: employment/
          weight: 7 



params:
    description: "This website serves as a central hub for Thorsten Wübbena’s academic work."
    author: Thorsten Wübbena
    DateFormat: "January 2026"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["publications", "presentations", "data", "projects", "misc", "memberships", "employment"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Thorsten Wübbena
          subtitle: "Head of the DH Lab and the research group *Digitality in Historical Research* at the [Leibniz Institute of European History](https://www.ieg-mainz.de/en/) (Mainz)"
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Publications
              url: publications/
            - name: Presentations | Poster | Conferences | Workshops
              url: presentations/
            - name: Data | Software
              url: data/
            - name: Projects
              url: projects/
            - name: Interviews | Clips | Misc
              url: misc/
            - name: Memberships | Committees
              url: memberships/
            - name: Employment history
              url: employment/


    socialIcons:
        - name: Location
          url: location/
        - name: Institutional Website
          url: https://www.ieg-mainz.de/en/person/wuebbena/
        - name: Mastodon
          url: https://fedihum.org/@ThWuebbena
        - name: ORCID
          url: https://orcid.org/0000-0001-8172-6097
        - name: Codeberg
          url: https://codeberg.org/wuebbena
        - name: GitHub
          url: https://github.com/wuebbena
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=GjBl3mQAAAAJ
        - name: LinkedIN
          url: https://de.linkedin.com/in/thorsten-w%C3%BCbbena-7a632043
        - name: Email
          url: mailto:wuebbena@ieg-mainz.de

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Thorsten Wübbena"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2